name: Generate Snake

# Controls when the action will run - Only when needed, not every 6 hours
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Run only on push to master (when you actually make changes)
  push:
    branches:
    - master
    paths-ignore:
      - 'README.md'
      - 'daily-activity.md'
  
  # Run weekly on Sundays at 00:00 UTC (once a week is enough)
  schedule:
    - cron: "0 0 * * 0"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # Use the official Platane/snk action directly (no custom setup needed)
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # Simple output - just what we need
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Push the content to output branch
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}