name: Generate Snake

# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    # runs every 12 hours
    - cron: "0 */12 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # Install system dependencies for canvas (from issue solutions)
      - name: Install Canvas Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libcairo2-dev \
            libpango1.0-dev \
            libjpeg-dev \
            libgif-dev \
            librsvg2-dev \
            pkg-config \
            python3-dev

      # Setup Node.js (canvas needs specific node version)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Pre-install canvas to avoid runtime issues
      - name: Pre-install Canvas
        run: |
          npm install canvas
        continue-on-error: true

      # Generates the snake using regular action (not svg-only)
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push the content of <build_dir> to a branch
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}